theme = "webstack"
version = "20.06.09"

baseURL = "https://nav.ryanjie.cn"
title = "Ryanjie"

[params]
    subtitle = "Stay Simple."

    # 横条logo
    logo = "https://cdn.jsdelivr.net/gh/Ryanjiena/Navigation@gh-pages/images/logo.png"

    # logo 图标
    logoM = "https://cdn.jsdelivr.net/gh/Ryanjiena/Navigation@gh-pages/images/logo.png"

    cdn = "https://cdn.jsdelivr.net/gh/Ryanjiena/Navigation@gh-pages"
    # cdn = "https://nav.ryanjie.cn"

    jinrishici = "true"
    busuanzi = "true"
