name: Deploy Hugo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build-Deply
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          # extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}

      - name: Sync Coding
        uses: GuoJuna/sync-repo-action@master
        with:
          source_repo_url: git@github.com:${{ github.repository }}.git
          source_branch: gh-pages
          dest_repo_url: git@e.coding.net:ryanjie/nvg.git
          dest_branch: gh-pages
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 部署到腾宝塔服务器
      # - name: Webhook
      #   uses: distributhor/workflow-webhook@v1
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
